### ISSUE TITLE
Suggestion for property names

### ISSUE THREAD

**Issue by cheton** [trendmicro-frontend/react-popover#1]
The `preferPlace` listed in the docs is <b>verb + noun</b>, for a better naming convention, <b>noun</b> or <b>adjective + noun</b> is a recommended practice for defining a property in any types (i.e. boolean, number, string, etc.), while <b>verb</b> or <b>verb + noun</b> is usually to define a property in <i>boolean</i> or <i>function</i> type. See following examples:

**Noun (or Adjective + Noun)**

Name | Type
----- | -----
id | string\|number
title | node
activeKey | any
activePage | number
placement | one of: 'top', 'right', 'bottom', 'left'

**Verb (or Verb + Noun)**

Name | Type
----- | -----
show | boolean
justified | boolean
pullLeft | boolean
enforceFocus | boolean
mountOnEnter | boolean 
getDimensionValue | function

---

For this case, I suggest you replace `preferPlace` with `placement`, which will look much better.

You can also refer to https://react-bootstrap.github.io/components.html#popover-props for details.

Name | Type | Default | Description
----- | ----- | ----- | -----
arrowOffsetLeft | number \| string | | The "left" position value for the Popover are for the Popover arrow.
arrowOffsetTop | number \| string | | The "top" position value for the Popover are for the Popover arrow.
placement | one of: 'top', 'right', 'bottom', 'left' | 'right' | Sets the direction the Popover is positioned towards.
positionLeft | number \| string | | The "left" position value for the Popover.
positionTop | number \| string | | The "top" position value for the Popover.
title | node | | Title content

**Comment by seawind543** [comment]
Fixed at v0.2.0
